#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# Only displays the part of the name after the first dash. 

for file in *;
do
    if [[ "$file" != .* ]];
then
        name_part=$(echo "$file" | cut -d'-' -f2-)

        echo "- $name_part"
    fi
done

